name: Notify Discord

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{"content":"Hello from GitHub Actions!"}' \
            "$DISCORD_WEBHOOK"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
